name: EcoStack Metrics Collection Template
description: "Reusable workflow template for EcoStack metrics collection across the organization"
on:
  workflow_call:

jobs:
  collect-metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    # Ensure this job has the necessary permissions
    permissions:
      contents: read
      id-token: write  # For enhanced security
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Shallow clone for faster checkout
          fetch-depth: 1
      
      # 🌱 MEASURE CARBON FOOTPRINT - Core metrics collection
      - name: Measure Carbon Footprint
        uses: EcoStackTech/metrics@v8.1.2
        # This action provides:
        # • True pipeline duration measurement (from commit/PR creation)
        # • Enhanced resource monitoring (CPU, memory, disk, network)
        # • Energy consumption data for API-side carbon calculations
        # • Pipeline efficiency insights
        # • Unified metrics structure for dashboard aggregation
        # • Common metrics (entity ID, location, category, department)
        # • Automatic API transmission to EcoStack
      
      # Optional: Post-metrics collection steps
      - name: Post-metrics summary
        if: always()
        run: |
          echo "📋 Metrics collection summary:"
          echo "   • Repository: ${{ github.repository }}"
          echo "   • Workflow: ${{ github.workflow }}"
          echo "   • Job: ${{ github.job }}"
          echo "   • Run ID: ${{ github.run_id }}"
          echo "   • Runner: ${{ runner.name }}"
          echo "   • Event: ${{ github.event_name }}"
          echo ""
          echo "✅ Metrics sent to EcoStack API successfully!"
          echo "🌱 Your environmental impact has been measured and recorded."
      
      # Optional: Add any post-processing or notifications
      - name: Notify team (optional)
        if: always() && github.event_name == 'push'
        run: |
          echo "🔔 Metrics collection completed for ${{ github.repository }}"
          echo "📊 Check your EcoStack dashboard for detailed insights"
          echo "🌍 Help your team reduce their carbon footprint!"

# Example usage in any repository:
#
# name: Use EcoStack Metrics
# on: [push, pull_request]
# jobs:
#   metrics:
#     uses: ./.github/workflows/ecostack-metrics.yml
#
#   # Your other jobs...
#   build:
#     needs: metrics
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - run: echo "Building after metrics collection..."
