name: EcoStack Metrics Collection
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linting
        run: npm run lint
      
      - name: Run tests
        run: npm test
      
      - name: Build application
        run: npm run build
      
      - name: Run security audit
        run: npm audit --audit-level moderate
      
      # 🌱 MEASURE CARBON FOOTPRINT - Place at the end for best results!
      - name: Measure Carbon Footprint
        uses: EcoStackTech/metrics@v2.0.0
        # This action will:
        # • Measure the entire pipeline duration (from commit to completion)
        # • Collect energy consumption data for accurate carbon calculations
        # • Provide detailed insights into pipeline efficiency
        # • Send unified metrics to EcoStack API with common aggregation fields
        # • Enable dashboard aggregation across multiple sources


